global using System;
global using System.IO;
global using System.Text;
global using System.Collections.Generic;
global using System.Net.Http;
global using System.Net.Mime;
global using System.Net.Http.Headers;
global using System.Threading.Tasks;
global using Jinget.Handlers.ExternalServiceHandlers.ServiceHandler;
global using Jinget.Handlers.ExternalServiceHandlers.ServiceHandler.Factory;
global using static Jinget.Core.Utilities.XmlUtility;
global using static Jinget.Core.Utilities.HumanizerUtility;
global using static Jinget.Core.Utilities.Http.HeaderUtility;