// Global using directives

global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Data;
global using System.Data.SqlClient;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Security.Claims;
global using System.Text;
global using System.Threading.Tasks;
global using Dapper;
global using Jinget.Core.CodeDom;
global using Jinget.Core.Enumerations;
global using Jinget.Core.Exceptions;
global using Jinget.Core.ExpressionToSql;
global using Jinget.Core.ExpressionToSql.Internal;
global using Jinget.Core.ExtensionMethods;
global using Jinget.Core.ExtensionMethods.Collections;
global using Jinget.Core.ExtensionMethods.Dapper;
global using Jinget.Core.ExtensionMethods.Database.SqlClient;
global using Jinget.Core.ExtensionMethods.Enums;
global using Jinget.Core.ExtensionMethods.Expressions;
global using Jinget.Core.ExtensionMethods.ExpressionToSql;
global using Jinget.Core.ExtensionMethods.Generics;
global using Jinget.Core.ExtensionMethods.Http;
global using Jinget.Core.ExtensionMethods.Reflection;
global using Jinget.Core.Tests._BaseData;
global using Jinget.Core.Types;
global using Jinget.Core.Utilities;
global using Jinget.Core.Utilities.Enum;
global using Jinget.Core.Utilities.Expressions;
global using Jinget.Core.Utilities.Http;
global using Jinget.Core.Utilities.Json;
global using Jinget.Core.Utilities.Parser.DatabaseParser.SqlServer;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Moq;
global using Newtonsoft.Json;
global using static Jinget.Core.ExtensionMethods.ObjectExtensions;
global using static Jinget.Core.Tests._BaseData.SampleEnum;
global using static Jinget.Core.Tests._BaseData.TestClass;